// client/src/Frontend/Pages/LandingPage.tsx
import { CONTRACT_ADDRESS } from '@dfdao/contracts';
import { address } from '@dfdao/serde';
import React from 'react';
import { useHistory } from 'react-router-dom';
import styled from 'styled-components';
import { Btn } from '../Components/Btn';
import { EmSpacer, Link, Spacer, Title } from '../Components/CoreUI';
import { EmailCTA, EmailCTAMode } from '../Components/Email';
import { Modal } from '../Components/Modal';
import { HideSmall, Text, White } from '../Components/Text';
import dfstyles from '../Styles/dfstyles';
import { LandingPageRoundArt } from '../Views/LandingPageRoundArt';
import { LeadboardDisplay } from '../Views/Leaderboard';

export const enum LandingPageZIndex {
  Background = 0,
  Canvas = 1,
  BasePage = 2,
}

const links = {
  twitter: 'http://twitter.com/darkforest_eth',
  email: 'mailto:ivan@0xparc.org',
  blog: 'https://blog.zkga.me/',
  discord: 'https://discord.gg/2u2TN6v8r6',
  github: 'https://github.com/darkforest-eth',
  wiki: 'https://dfwiki.net/wiki/Main_Page',
  plugins: 'https://plugins.zkga.me/',
};

const defaultAddress = address(CONTRACT_ADDRESS);

const ButtonWrapper = styled.div`
  display: flex;
  justify-content: center;
  gap: 8px;
  flex-direction: row;

  @media only screen and (max-device-width: 1000px) {
    grid-template-columns: auto;
    flex-direction: column;
  }

  --df-button-color: ${dfstyles.colors.dfgreen};
  --df-button-border: 1px solid ${dfstyles.colors.dfgreen};
  --df-button-hover-background: ${dfstyles.colors.dfgreen};
  --df-button-hover-border: 1px solid ${dfstyles.colors.dfgreen};
`;

export default function LandingPage() {
  const history = useHistory();

  return (
    <>
      <PrettyOverlayGradient />
      <Hiring />

      <Page>
        <OnlyMobile>
          <Spacer height={8} />
        </OnlyMobile>
        <HideOnMobile>
          <Spacer height={150} />
        </HideOnMobile>

        <MainContentContainer>
          <Header>
            <LinkContainer>
              <Link to={links.email}>email</Link>
              <Spacer width={4} />
              <Link to={links.blog}>blog</Link>
              <Spacer width={4} />

              <a className={'link-twitter'} href={links.twitter}>
                <span className={'icon-twitter'}></span>
              </a>
              <Spacer width={4} />
              <a className={'link-discord'} href={links.discord}>
                <span className={'icon-discord'}></span>
              </a>
              <Spacer width={4} />
              <a className={'link-github'} href={links.github}>
                <span className={'icon-github'}></span>
              </a>

              <Spacer width={4} />
              <Link to={links.plugins}>plugins</Link>
              <Spacer width={4} />
              <Link to={links.wiki}>wiki</Link>
            </LinkContainer>

            <OnlyMobile>
              <Spacer height={4} />
            </OnlyMobile>
            <HideOnMobile>
              <Spacer height={16} />
            </HideOnMobile>

            <LandingPageRoundArt />

            <p>
              <White>Dark Forest</White> <Text>zkSNARK space warfare</Text>
              <br />
              <Text>Round 5: </Text>
              <White>The Junk Wars</White>
            </p>

            <Spacer height={16} />

            <ButtonWrapper>
              <Btn size='large' onClick={() => history.push(`/lobby/${defaultAddress}`)}>
                Create Lobby
              </Btn>
              <Btn size='large' onClick={() => history.push(`/play/${defaultAddress}`)}>
                Enter Round 5
              </Btn>
              <Btn size='large' onClick={() => history.push(`/events`)}>
                Events
              </Btn>
            </ButtonWrapper>
          </Header>
          <EmSpacer height={3} />
          Ways to get Involved
          <EmSpacer height={1} />
          <Involved>
            <InvolvedItem
              href='https://blog.zkga.me/hosting-a-dark-forest-community-round'
              style={{
                backgroundImage: "url('/get_involved/community_round.png')",
              }}
            ></InvolvedItem>
            <InvolvedItem
              href='https://github.com/darkforest-eth/plugins#adding-your-plugin'
              style={{
                backgroundImage: "url('/get_involved/write_plugin.png')",
              }}
            ></InvolvedItem>
            <InvolvedItem
              href='https://github.com/darkforest-eth/plugins#reviewer-guidelines'
              style={{
                backgroundImage: "url('/get_involved/reveiw_plugin.png')",
              }}
            ></InvolvedItem>
            <InvolvedItem
              href='https://blog.zkga.me/renderer-plugin-contest'
              style={{
                backgroundImage: "url('/get_involved/plugin_render.png')",
              }}
            ></InvolvedItem>
            <InvolvedItem
              href='https://blog.zkga.me/introducing-dark-forest-lobbies'
              style={{
                backgroundImage: "url('/get_involved/lobby.png')",
              }}
            ></InvolvedItem>
          </Involved>
          <EmSpacer height={3} />
          <HallOfFame style={{ color: dfstyles.colors.text }}>
            <HallOfFameTitle>Space Masters</HallOfFameTitle>
            <Spacer height={8} />
            <table>
              <tbody>
                <TRow>
                  <td>
                    <HideSmall>v</HideSmall>0.1
                  </td>
                  <td>
                    02/22/<HideSmall>20</HideSmall>20
                  </td>
                  <td>
                    <a href='https://twitter.com/zoink'>Dylan Field</a>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <HideSmall>v</HideSmall>0.2
                  </td>
                  <td>
                    06/24/<HideSmall>20</HideSmall>20
                  </td>
                  <td>Nate Foss</td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v3-rules'>
                      <HideSmall>v</HideSmall>0.3
                    </Link>
                  </td>
                  <td>
                    08/07/<HideSmall>20</HideSmall>20
                  </td>
                  <td>
                    <Link to='https://twitter.com/hideandcleanse'>@hideandcleanse</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v4-recap'>
                      <HideSmall>v</HideSmall>0.4
                    </Link>
                  </td>
                  <td>
                    10/02/<HideSmall>20</HideSmall>20
                  </td>
                  <td>
                    <Link to='https://twitter.com/jacobrosenthal'>Jacob Rosenthal</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v5-winners'>
                      <HideSmall>v</HideSmall>0.5
                    </Link>
                  </td>
                  <td>
                    12/25/<HideSmall>20</HideSmall>20
                  </td>
                  <td>0xb05d9542...</td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v6-r1-wrapup'>
                      <HideSmall>v</HideSmall>0.6 round 1
                    </Link>
                  </td>
                  <td>
                    05/22/<HideSmall>20</HideSmall>21
                  </td>
                  <td>
                    <Link to='https://twitter.com/adietrichs'>Ansgar Dietrichs</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v6-r2-wrapup'>
                      <HideSmall>v</HideSmall>0.6 round 2
                    </Link>
                  </td>
                  <td>
                    07/07/<HideSmall>20</HideSmall>21
                  </td>
                  <td>
                    <Link to='https://twitter.com/orden_gg'>@orden_gg</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v6-r3-wrapup'>
                      <HideSmall>v</HideSmall>0.6 round 3
                    </Link>
                  </td>
                  <td>
                    08/22/<HideSmall>20</HideSmall>21
                  </td>
                  <td>
                    <Link to='https://twitter.com/dropswap_gg'>@dropswap_gg</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v6-r4-wrapup'>
                      <HideSmall>v</HideSmall>0.6 round 4
                    </Link>
                  </td>
                  <td>
                    10/01/<HideSmall>20</HideSmall>21
                  </td>
                  <td>
                    <Link to='https://twitter.com/orden_gg'>@orden_gg</Link>
                  </td>
                </TRow>
                <TRow>
                  <td>
                    <Link to='https://blog.zkga.me/v6-r5-wrapup'>
                      <HideSmall>v</HideSmall>0.6 round 5
                    </Link>
                  </td>
                  <td>
                    02/18/<HideSmall>20</HideSmall>22
                  </td>
                  <td>
                    <Link to='https://twitter.com/d_fdao'>@d_fdao</Link>
                    {' + '}
                    <Link to='https://twitter.com/orden_gg'>@orden_gg</Link>
                  </td>
                </TRow>
              </tbody>
            </table>
          </HallOfFame>
          <Spacer height={32} />
          <EmailWrapper>
            <EmailCTA mode={EmailCTAMode.SUBSCRIBE} />
          </EmailWrapper>
        </MainContentContainer>

        <Spacer height={128} />

        <LeadboardDisplay />

        <Spacer height={256} />
      </Page>
    </>
  );
}

const PrettyOverlayGradient = styled.div`
  width: 100vw;
  height: 100vh;
  background: linear-gradient(to left top, rgba(74, 74, 74, 0.628), rgba(60, 1, 255, 0.2)) fixed;
  background-position: 50%, 50%;
  display: inline-block;
  position: fixed;
  top: 0;
  left: 0;
  z-index: -1;
`;

const Header = styled.div`
  text-align: center;
`;

const EmailWrapper = styled.div`
  display: flex;
  flex-direction: row;
`;

const TRow = styled.tr`
  & td:first-child {
    color: ${dfstyles.colors.subtext};
  }
  & td:nth-child(2) {
    padding-left: 12pt;
  }
  & td:nth-child(3) {
    text-align: right;
    padding-left: 16pt;
  }
`;

const MainContentContainer = styled.div`
  max-width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
`;

const Page = styled.div`
  position: absolute;
  width: 100vw;
  max-width: 100vw;
  height: 100%;
  color: white;
  font-size: ${dfstyles.fontSize};
  display: flex;
  flex-direction: column;
  align-items: center;
  z-index: ${LandingPageZIndex.BasePage};
`;

const HallOfFameTitle = styled.div`
  color: ${dfstyles.colors.subtext};
  display: inline-block;
  border-bottom: 1px solid ${dfstyles.colors.subtext};
  line-height: 1em;
`;

export const LinkContainer = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;

  a {
    margin: 0 6pt;
    transition: color 0.2s;
    display: flex;
    justify-content: center;
    align-items: center;

    &:hover {
      cursor: pointer;
      &.link-twitter {
        color: ${dfstyles.colors.icons.twitter};
      }
      &.link-github {
        color: ${dfstyles.colors.icons.github};
      }
      &.link-discord {
        color: ${dfstyles.colors.icons.discord};
      }
      &.link-blog {
        color: ${dfstyles.colors.icons.blog};
      }
      &.link-email {
        color: ${dfstyles.colors.icons.email};
      }
    }
  }
`;

function Hiring() {
  return (
    <HideOnMobile>
      <Modal contain={['top', 'left', 'right']} initialX={50} initialY={50}>
        <Title slot='title'>Dark Forest is Hiring!</Title>
        <div style={{ maxWidth: '300px', textAlign: 'justify' }}>
          We are looking for experienced full stack and solidity developers to join our team! If you
          like what you see,{' '}
          <Link to='https://docs.google.com/forms/d/e/1FAIpQLSdaWvjxX4TrDDLidPXtgk6UW3rC082rpvi3AIPkCPxAahg_rg/viewform?usp=sf_link'>
            consider applying
          </Link>
          . If you know someone who you think would be a great fit for our team,{' '}
          <Link to='https://docs.google.com/forms/d/e/1FAIpQLScku_bQDbkPqpHrwBzOBfQ4SV6Nw6Tgxi6zWQL8Bb0olyBE3w/viewform?usp=sf_link'>
            please refer them here
          </Link>
          .
          <br />
          <br />
          Learn more about the role{' '}
          <Link to='https://ivanchub.notion.site/Dark-Forest-is-Hiring-ad1f0cbe816640fb9b4c663dacaaca04'>
            here
          </Link>
          .
        </div>
      </Modal>
    </HideOnMobile>
  );
}

const HideOnMobile = styled.div`
  @media only screen and (max-device-width: 1000px) {
    display: none;
  }
`;

const OnlyMobile = styled.div`
  @media only screen and (min-device-width: 1000px) {
    display: none;
  }
`;

const Involved = styled.div`
  width: 100%;
  padding-left: 16px;
  padding-right: 16px;
  display: grid;
  grid-template-columns: auto auto;
  gap: 10px;
  grid-auto-rows: minmax(100px, auto);

  @media only screen and (max-device-width: 1000px) {
    grid-template-columns: auto;
  }
`;

const InvolvedItem = styled.a`
  height: 150px;
  display: inline-block;
  margin: 4px;
  padding: 4px 8px;

  background-color: ${dfstyles.colors.backgroundlighter};
  background-size: cover;
  background-position: 50% 50%;
  background-repeat: no-repeat;

  cursor: pointer;
  transition: transform 200ms;
  &:hover {
    transform: scale(1.03);
  }
  &:hover:active {
    transform: scale(1.05);
  }
`;

const HallOfFame = styled.div`
  @media only screen and (max-device-width: 1000px) {
    font-size: 70%;
  }
`;

// client/src/Frontend/Pages/LandingPage.svelte
<script lang="ts">
  import { CONTRACT_ADDRESS } from '@dfdao/contracts';
  import { address } from '@dfdao/serde';
  import { push } from 'svelte-spa-router';
  import IconLink from '../Components/IconLink.svelte';
  import Link from '../Components/Link.svelte';
  import LandingPageRoundArt from '../Views/LandingPageRoundArt.svelte';

  const links = {
    twitter: 'http://twitter.com/darkforest_eth',
    email: 'mailto:ivan@0xparc.org',
    blog: 'https://blog.zkga.me/',
    discord: 'https://discord.gg/2u2TN6v8r6',
    github: 'https://github.com/darkforest-eth',
    wiki: 'https://dfwiki.net/wiki/Main_Page',
    plugins: 'https://plugins.zkga.me/',
  };

  const defaultAddress = address(CONTRACT_ADDRESS);
</script>

<div class="PrettyOverlayGradient" />
<div class="Page">
  <div class="MainContentContainer">
    <div class="Header">
      <div class="LinkContainer">
        <Link to={links.email} openNewTab>email</Link>
        <Link to={links.blog} openNewTab>blog</Link>
        <IconLink to={links.twitter} icon="twitter" />
        <IconLink to={links.discord} icon="discord" />
        <IconLink to={links.github} icon="github" />
        <Link to={links.plugins} openNewTab>plugins</Link>
        <Link to={links.wiki} openNewTab>wiki</Link>
      </div>

      <LandingPageRoundArt />

      <p>
        <span class="White">Dark Forest</span>
        <span class="Text">zkSNARK space warfare</span>
        <br />
        <span class="Text">Round 5:</span>
        <span class="White">The Junk Wars</span>
      </p>

      <div class="ButtonWrapper">
        <df-button size="large" on:click={() => push(`/lobby/${defaultAddress}`)}
          >Create Lobby</df-button
        >
        <df-button size="large" on:click={() => push(`/play/${defaultAddress}`)}
          >Enter Round 5</df-button
        >
        <df-button size="large" on:click={() => push(`/events`)}>Events</df-button>
      </div>
    </div>

    Ways to get Involved

    <div class="Involved">
      <a
        class="InvolvedItem"
        href="https://blog.zkga.me/hosting-a-dark-forest-community-round"
        style:background-image="url('/get_involved/community_round.png')"
      />
      <a
        class="InvolvedItem"
        href="https://github.com/darkforest-eth/plugins#adding-your-plugin"
        style:background-image="url('/get_involved/write_plugin.png')"
      />
      <a
        class="InvolvedItem"
        href="https://github.com/darkforest-eth/plugins#reviewer-guidelines"
        style:background-image="url('/get_involved/reveiw_plugin.png')"
      />
      <a
        class="InvolvedItem"
        href="https://blog.zkga.me/renderer-plugin-contest"
        style:background-image="url('/get_involved/plugin_render.png')"
      />
      <a
        class="InvolvedItem"
        href="https://blog.zkga.me/introducing-dark-forest-lobbies"
        style:background-image="url('/get_involved/lobby.png')"
      />
    </div>
  </div>
</div>

<style>
  .PrettyOverlayGradient {
    width: 100vw;
    height: 100vh;
    background: linear-gradient(to left top, rgba(74, 74, 74, 0.628), rgba(60, 1, 255, 0.2)) fixed;
    background-position: 50%, 50%;
    display: inline-block;
    position: fixed;
    top: 0;
    left: 0;
    z-index: -1;
  }

  .Page {
    position: absolute;
    width: 100vw;
    max-width: 100vw;
    height: 100%;
    color: white;
    font-size: var(--df-font-size);
    display: flex;
    flex-direction: column;
    align-items: center;
    /* did this need to be a variable? */
    z-index: 2;

    /* Fuck spacers */
    margin-top: 150px;
  }

  .MainContentContainer {
    max-width: 100%;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: space-between;
  }

  .Header {
    text-align: center;

    /* Fuck spacers */
    margin-bottom: 3em;
  }

  .LinkContainer {
    display: flex;
    justify-content: center;
    align-items: center;

    /* Fuck spacers */
    margin-bottom: 16px;
    column-gap: 20px;
  }

  .ButtonWrapper {
    display: flex;
    justify-content: center;
    gap: 8px;
    flex-direction: row;

    /* Fuck spacers */
    margin-top: 16px;

    --df-button-color: var(--df-colors-dfgreen);
    --df-button-border: 1px solid var(--df-colors-dfgreen);
    --df-button-hover-background: var(--df-colors-dfgreen);
    --df-button-hover-border: 1px solid var(--df-colors-dfgreen);
  }

  .Involved {
    width: 100%;
    padding-left: 16px;
    padding-right: 16px;
    display: grid;
    grid-template-columns: auto auto;
    gap: 10px;
    grid-auto-rows: minmax(100px, auto);

    /* Fuck spacers */
    margin-top: 1em;
    margin-bottom: 3em;
  }

  .InvolvedItem {
    height: 150px;
    display: inline-block;
    margin: 4px;
    padding: 4px 8px;

    background-color: var(--df-colors-backgroundlighter);
    background-size: cover;
    background-position: 50% 50%;
    background-repeat: no-repeat;

    cursor: pointer;
    transition: transform 200ms;
  }
  .InvolvedItem:hover,
  .InvolvedItem:active {
    transform: scale(1.03);
  }

  @media only screen and (max-device-width: 1000px) {
    .Page {
      /* Fuck spacers */
      margin-top: 8px;
    }

    .LinkContainer {
      /* Fuck spacers */
      margin-bottom: 4px;
    }

    .ButtonWrapper {
      grid-template-columns: auto;
      flex-direction: column;
    }

    .Involved {
      grid-template-columns: auto;
    }
  }

  .White {
    color: var(--df-colors-dfwhite);
  }
  .Text {
    color: var(--df-colors-text);
  }
</style>
